from Base.base import Base
from selenium.webdriver.common.keys import Keys
def messageFB(self):
    ten_nguoi_nhan=self.driver.find_element('xpath','//div[@class="x1e56ztr x1xmf6yo"]//h1[@class="x1heor9g x1qlqyl8 x1pd3egz x1a2a7pz"]')
    ten_nguoi_nhan_text = ten_nguoi_nhan.text
    tin_nhan_1= Base(self.driver).getElement(('xpath','//p[@class="xat24cr xdj266r"]'))
    tin_nhan_1.send_keys(f'Chào {ten_nguoi_nhan_text}!')
    tin_nhan_1.send_keys(Keys.SHIFT + Keys.ENTER)
    tin_nhan_2= Base(self.driver).getElement(('xpath','//p[@class="xat24cr xdj266r xdpxx8g"]'))
    tin_nhan_2.send_keys('Socialyze Asia rất hân hạnh khi bạn đã quan tâm đến báo cáo “Đêm Nhạc BLACKPINK - Người Việt Ủng Hộ Nhiều Hơn Hay Phản Đối Nhiều Hơn')
    tin_nhan_2.send_keys(Keys.SHIFT + Keys.ENTER)
    tin_nhan_2.send_keys('Bản báo cáo này sẽ mang lại cho bạn cái nhìn đa chiều về đêm nhạc BLACKPINK,')
    tin_nhan_2.send_keys(Keys.SHIFT+Keys.ENTER)
    tin_nhan_2.send_keys('- Tệp khách hàng của bạn đang quan tâm đến các chủ đề nào xoay quanh sự kiện BLACKPINK này?')
    tin_nhan_2.send_keys(Keys.SHIFT+Keys.ENTER)
    tin_nhan_2.send_keys('- Sự kiện này có tác động đến quyết định, hành vi của cả người trẻ và người lớn tuổi như thế nào?')
    tin_nhan_2.send_keys(Keys.SHIFT+Keys.ENTER)
    tin_nhan_2.send_keys('- Khách hàng tiềm năng đang quan tâm đến khía cạnh nào của sự kiện BLACKPINK?”...')
    tin_nhan_2.send_keys(Keys.SHIFT+Keys.ENTER)
    tin_nhan_2.send_keys('- Tất cả sẽ có trong “Đêm Nhạc BLACKPINK - Người Việt Ủng Hộ Nhiều Hơn Hay Phản Đối Nhiều Hơn”.')
    tin_nhan_2.send_keys(Keys.SHIFT+Keys.ENTER)
    tin_nhan_2.send_keys('- Socialyze Asia mang đến cho bạn bức tranh tổng quan xoay quanh sự kiện này một cách nhanh chóng, để kịp thời đưa ra các quyết định đúng đắn.')
    tin_nhan_2.send_keys(Keys.SHIFT+Keys.ENTER)
    tin_nhan_2.send_keys('- Để không bỏ lỡ bất kỳ thông tin mới nào liên quan đến [sản phẩm/dịch vụ] của Socialyze Asia, chúng tôi sẽ gửi đến bạn các thông tin về [sản phẩm/dịch vụ] thông qua thư điện tử.')
    tin_nhan_2.send_keys(Keys.SHIFT+Keys.ENTER)
    tin_nhan_2.send_keys('- Nếu bạn có bất kỳ câu hỏi hoặc thắc mắc nào, vui lòng liên hệ với chúng tôi qua số điện thoại (+84) 0903983811 hoặc Email: info@socialyze.asia')
    tin_nhan_2.send_keys(Keys.SHIFT+Keys.ENTER)
    tin_nhan_2.send_keys('---ĐĂNG KÝ NGAY ĐỂ NHẬN MIỄN PHÍ BÁO CÁO ĐẦY ĐỦ---')
    tin_nhan_2.send_keys(Keys.SHIFT+Keys.ENTER)
    tin_nhan_2.send_keys('Chân thành cảm ơn bạn đã tin tưởng và sử dụng sản phẩm/dịch vụ của Socialyze Asia.')
    tin_nhan_2.send_keys(Keys.SHIFT+Keys.ENTER)
    tin_nhan_2.send_keys('Trân trọng,')
    tin_nhan_2.send_keys(Keys.ENTER)
    return messageFB

def messageLinkedin(self):
    ten_nguoi_nhan= self.driver.find_element('xpath','//h1[@class="text-heading-xlarge inline t-24 v-align-middle break-words"]')
    ten_nguoi_nhan_text = ten_nguoi_nhan.text
    msg = "Chào {}!\nSocialyze Asia rất hân hạnh khi bạn đã quan tâm đến báo cáo “Đêm Nhạc BLACKPINK - Người Việt Ủng Hộ Nhiều Hơn Hay Phản Đối Nhiều Hơn”\nBản báo cáo này sẽ mang lại cho bạn cái nhìn đa chiều về đêm nhạc BLACKPINK,\n<3 Tệp khách hàng của bạn đang quan tâm đến các chủ đề nào xoay quanh sự kiện BLACKPINK này?\n<3 Sự kiện này có tác động đến quyết định, hành vi của cả người trẻ và người lớn tuổi như thế nào?\n<3 Khách hàng tiềm năng đang quan tâm đến khía cạnh nào của sự kiện BLACKPINK?”...\n<3 Tất cả sẽ có trong “Đêm Nhạc BLACKPINK - Người Việt Ủng Hộ Nhiều Hơn Hay Phản Đối Nhiều Hơn”.\n<3 Socialyze Asia mang đến cho bạn bức tranh tổng quan xoay quanh sự kiện này một cách nhanh chóng, để kịp thời đưa ra các quyết định đúng đắn.\n\n<3 Để không bỏ lỡ bất kỳ thông tin mới nào liên quan đến [sản phẩm/dịch vụ] của Socialyze Asia, chúng tôi sẽ gửi đến bạn các thông tin về [sản phẩm/dịch vụ] thông qua thư điện tử.\n<3 Nếu bạn có bất kỳ câu hỏi hoặc thắc mắc nào, vui lòng liên hệ với chúng tôi qua số điện thoại (+84) 0903983811 hoặc Email: info@socialyze.asia\n<3 <3 ĐĂNG KÝ NGAY ĐỂ NHẬN MIỄN PHÍ BÁO CÁO ĐẦY ĐỦ <3 <3\n\nChân thành cảm ơn bạn đã tin tưởng và sử dụng sản phẩm/dịch vụ của Socialyze Asia.\nTrân trọng,".format(ten_nguoi_nhan_text)
    return msg

def messageZalo(self):
    ten_nguoi_nhan= Base(self.driver).getElement(('xpath','//div-b18[@class="header-title flx flx-al-c flex-1"]'))
    ten_nguoi_nhan_text = ten_nguoi_nhan.text
    tinnhan=Base(self.driver).getElement(('xpath','//div[@data-translate-placeholder="STR_MESSAGE_TO"]'))
    tinnhan.send_keys(f'Chào {ten_nguoi_nhan_text}!')
    tinnhan.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan2=Base(self.driver).getElement(('xpath','//div[@id="input_line_1"]'))
    tinnhan2.send_keys('Socialyze Asia rất hân hạnh khi bạn đã quan tâm đến báo cáo “Đêm Nhạc BLACKPINK - Người Việt Ủng Hộ Nhiều Hơn Hay Phản Đối Nhiều Hơn”')
    tinnhan2.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan3=Base(self.driver).getElement(('xpath','//div[@id="input_line_2"]'))
    tinnhan3.send_keys('Bản báo cáo này sẽ mang lại cho bạn cái nhìn đa chiều về đêm nhạc BLACKPINK,')
    tinnhan3.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan4=Base(self.driver).getElement(('xpath','//div[@id="input_line_3"]'))
    tinnhan4.send_keys('- Tệp khách hàng của bạn đang quan tâm đến các chủ đề nào xoay quanh sự kiện BLACKPINK này?')
    tinnhan4.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan5=Base(self.driver).getElement(('xpath','//div[@id="input_line_4"]'))
    tinnhan5.send_keys('- Sự kiện này có tác động đến quyết định, hành vi của cả người trẻ và người lớn tuổi như thế nào?')
    tinnhan5.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan6=Base(self.driver).getElement(('xpath','//div[@id="input_line_5"]'))
    tinnhan6.send_keys('- Khách hàng tiềm năng đang quan tâm đến khía cạnh nào của sự kiện BLACKPINK?”...')
    tinnhan6.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan7=Base(self.driver).getElement(('xpath','//div[@id="input_line_6"]'))
    tinnhan7.send_keys('- Tất cả sẽ có trong “Đêm Nhạc BLACKPINK - Người Việt Ủng Hộ Nhiều Hơn Hay Phản Đối Nhiều Hơn”.')
    tinnhan7.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan8=Base(self.driver).getElement(('xpath','//div[@id="input_line_7"]'))
    tinnhan8.send_keys('- Socialyze Asia mang đến cho bạn bức tranh tổng quan xoay quanh sự kiện này một cách nhanh chóng, để kịp thời đưa ra các quyết định đúng đắn.')
    tinnhan8.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan9=Base(self.driver).getElement(('xpath','//div[@id="input_line_8"]'))
    tinnhan9.send_keys('- Để không bỏ lỡ bất kỳ thông tin mới nào liên quan đến [sản phẩm/dịch vụ] của Socialyze Asia, chúng tôi sẽ gửi đến bạn các thông tin về [sản phẩm/dịch vụ] thông qua thư điện tử.')
    tinnhan9.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan10=Base(self.driver).getElement(('xpath','//div[@id="input_line_9"]'))
    tinnhan10.send_keys('- Nếu bạn có bất kỳ câu hỏi hoặc thắc mắc nào, vui lòng liên hệ với chúng tôi qua số điện thoại (+84) 0903983811 hoặc Email: info@socialyze.asia')
    tinnhan10.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan11=Base(self.driver).getElement(('xpath','//div[@id="input_line_10"]'))
    tinnhan11.send_keys('--- ĐĂNG KÝ NGAY ĐỂ NHẬN MIỄN PHÍ BÁO CÁO ĐẦY ĐỦ ---')
    tinnhan11.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan12=Base(self.driver).getElement(('xpath','//div[@id="input_line_11"]'))
    tinnhan12.send_keys('Chân thành cảm ơn bạn đã tin tưởng và sử dụng sản phẩm/dịch vụ của Socialyze Asia.')
    tinnhan12.send_keys(Keys.SHIFT + Keys.ENTER)
    tinnhan13=Base(self.driver).getElement(('xpath','//div[@id="input_line_12"]'))
    tinnhan13.send_keys('Trân trọng,')
    Base(self.driver).click_element(('xpath','//div[@data-translate-inner="STR_SEND"]'))
    return messageZalo